name: Petar Ivanov
bio: '...or just Pesho :")'

# main text of home
picture: 'assets/images/profile.jpg'

# url: http://pesho.info
url: http://petar-ivanov.github.io/pesho.info
# your url: http://USERNAME.github.io

permalink: /:title/

markdown: kramdown
highlighter: rouge

analytics-google: 'UA-42975539-2'
disqus: peshoinfo

# if you don't have any of social below, comment the line
cv: https://github.com/petar-ivanov/cv/raw/master/CV-Petar-Ivanov.pdf
#facebook: myfacebook
#twitter: mytwitter
#instagram: myinstagram
#linkedin: mylinkedin
#youtube: myyoutube
#spotify: myspotify
photos: https://picasaweb.google.com/109307985285518150648  # Pesho's public Picasa album
github: petar-ivanov
email: peter.ivanov89@gmail.com
# TODO: photos
rss: true
# TODO: RSS

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: false 

# if you don't need about or blog, comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# do you want some animations?
animation: true

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

defaults:
  -
    scope:
      path: ""
      layout: "post"
    values:
      blog: true
      # permalink: /:title/
      # category: "bg"

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, screen-shot.png, travis.sh]
